const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n), fmt=d=>new Date(d).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});
const future=(days,h=18)=>{const d=new Date();d.setDate(d.getDate()+days);d.setHours(h,0,0,0);return d.toISOString()};
const seed={notices:[{id:1,schoolClass:'ENEM 2026',title:'Tema da próxima redação',text:'Leiam o repertório sobre inclusão digital antes da aula de argumentação.'},{id:2,schoolClass:'ENEM 2026',title:'Plantão de dúvidas',text:'O suporte por vídeo estará disponível na quinta-feira, às 19h.'}],lessons:[{id:1,title:'Argumentação que convence',date:future(1),content:'Como transformar opinião em argumento bem desenvolvido.',activity:'Escreva um parágrafo com tese, causa e consequência.',material:'Mapa da argumentação',phase:'Antes da aula'},{id:2,title:'Repertório sociocultural',date:future(3),content:'Como escolher repertórios pertinentes e produtivos.',activity:'Associe três repertórios a temas do ENEM.',material:'Banco de repertórios',phase:'Durante a aula'},{id:3,title:'Coesão e progressão',date:future(5),content:'Conectivos, retomadas e sequência lógica entre ideias.',activity:'Reescreva um parágrafo melhorando a coesão.'},{id:4,title:'Proposta de intervenção',date:future(8),content:'Os cinco elementos de uma proposta completa.',activity:'Monte uma proposta detalhada para o tema da semana.'},{id:5,title:'Simulado comentado',date:future(12),content:'Produção completa e análise coletiva.',activity:'Produza uma redação completa em 90 minutos.'}],essays:[{id:1,title:'Os desafios da inclusão digital no Brasil',status:'Corrigida',grade:880},{id:2,title:'A valorização da cultura brasileira',status:'Em correção'}],messages:[{id:1,from:'gestor',text:'Oi, Ana! Pode enviar suas dúvidas por aqui.',time:'18:20'}],students:{'ENEM 2026':[{name:'Ana Clara',initials:'AC',status:'Em dia',paid:399.8,pending:0},{name:'João Pedro',initials:'JP',status:'Pendente',paid:199.9,pending:199.9},{name:'Marina Souza',initials:'MS',status:'Em dia',paid:399.8,pending:0},{name:'Lucas Lima',initials:'LL',status:'Atrasado',paid:199.9,pending:399.8}],'Intensivo Outubro':[{name:'Beatriz Alves',initials:'BA',status:'Em dia',paid:249.9,pending:0},{name:'Rafael Melo',initials:'RM',status:'Pendente',paid:0,pending:249.9}],'Redação Nota 1000':[{name:'Camila Rocha',initials:'CR',status:'Em dia',paid:599.8,pending:0},{name:'Pedro Nunes',initials:'PN',status:'Em dia',paid:599.8,pending:0},{name:'Lívia Martins',initials:'LM',status:'Atrasado',paid:299.9,pending:299.9}]}};
let data=JSON.parse(localStorage.getItem('leo-course-data')||'null')||seed, role=sessionStorage.getItem('leo-role')||'', view=location.hash.slice(1)||'inicio', selectedClass=localStorage.getItem('leo-class')||'ENEM 2026';
const save=()=>localStorage.setItem('leo-course-data',JSON.stringify(data));
const nav=[['inicio','⌂','Início'],['trilhas','⌁','Trilhas'],['redacoes','✎','Redações'],['suporte','◌','Suporte'],['perfil','○','Perfil']];
function go(v){view=v;location.hash=v;render();scrollTo(0,0)}
function shell(content){return `<header class="top"><button onclick="go('inicio')"><img src="logo.png" alt="Redação com Léo"></button><button class="avatar" onclick="go('perfil')">${role==='gestor'?'<img src="leonardo-avatar.png" alt="Professor Léo">':'AC'}</button></header><main>${content}</main><nav>${nav.map(([id,ic,n])=>`<button class="${view===id?'active':''}" onclick="go('${id}')"><b>${ic}</b><span>${n}</span></button>`).join('')}</nav>`}
function welcome(){return `<main class="welcome"><img class="logo" src="logo.png" alt="Redação com Léo"><img class="leo" src="leonardo-avatar.png" alt="Professor Leonardo Costa"><h1>Oi! Vamos entrar?</h1><p>Escolha seu perfil.</p><button class="role student" onclick="login('aluno')"><span>♟</span><strong>Sou aluno<small>Trilhas, redações e suporte</small></strong>›</button><button class="role teacher" onclick="login('gestor')"><span>✦</span><strong>Sou professor<small>Turmas, conteúdo e financeiro</small></strong>›</button></main>`}
function login(r){role=r;sessionStorage.setItem('leo-role',r);go('inicio')} function logout(){role='';sessionStorage.removeItem('leo-role');render()}
function classPicker(){return `<label class="picker">Turma<select onchange="selectedClass=this.value;localStorage.setItem('leo-class',selectedClass);render()">${Object.keys(data.students).map(c=>`<option ${c===selectedClass?'selected':''}>${c}</option>`).join('')}</select></label>`}
function notices(){const list=data.notices.filter(n=>role!=='gestor'||n.schoolClass===selectedClass);return `<section class="card notices"><div class="section-title"><h2>🔔 Avisos recentes</h2>${role==='gestor'?'<button class="mini" onclick="noticeModal()">＋ Aviso</button>':''}</div>${list.slice(0,3).map(n=>`<article><small>${esc(n.schoolClass)}</small><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p></article>`).join('')||'<p>Nenhum aviso publicado.</p>'}</section>`}
function home(){const next=data.lessons[0];return shell(`<div class="greeting"><div><small>${role==='gestor'?esc(selectedClass):'TURMA ENEM 2026'}</small><h1>Oi, ${role==='gestor'?'Léo':'Ana'}!</h1><p>${role==='gestor'?'Organize a turma e acompanhe os alunos.':'Continue sua trilha de redação.'}</p></div><img src="leonardo-avatar.png" alt="Professor Léo"></div>${role==='gestor'?classPicker():''}<div class="widgets">${notices()}<section class="card next"><h2>📅 Próxima aula</h2><span>${fmt(next.date)} · 18:00</span><h3>${esc(next.title)}</h3><p>60 min · na trilha</p><button onclick="go('trilhas')">Ver na trilha ›</button></section></div>${role==='gestor'?`<h2 class="block-title">Atalhos da turma</h2><div class="quick"><button onclick="noticeModal()">🔔<strong>Publicar aviso</strong></button><button onclick="materialModal()">📚<strong>Novo material</strong></button><button onclick="lessonModal()">＋<strong>Incluir aula</strong></button><button onclick="go('financeiro')">💳<strong>Financeiro</strong></button></div>`:`<h2 class="block-title">Continue aprendendo</h2><button class="continue" onclick="go('trilhas')"><i>📖</i><span><small>Etapa 2 de 5</small><strong>Construção da tese</strong><em>Conteúdo + atividade</em></span>›</button>`}`)}
function trails(){return shell(`<div class="heading"><small>${esc(selectedClass)}</small><h1>Trilha de aprendizagem</h1><p>${role==='gestor'?'Publique aulas e materiais em cada etapa.':'Avance etapa por etapa e entregue as atividades.'}</p>${role==='gestor'?'<div><button class="outline" onclick="materialModal()">📚 Material</button><button onclick="lessonModal()">＋ Nova aula</button></div>':''}</div><section class="trail">${data.lessons.map((l,i)=>`<article><div class="node ${i===0?'done':''}">${i===0?'✓':i+1}</div><div class="card step"><small>ETAPA ${i+1} · ${fmt(l.date)}</small><h2>${esc(l.title)}</h2><p>${esc(l.content)}</p>${l.material?`<div class="chip">📄 <span><strong>${esc(l.material)}</strong><small>${esc(l.phase)}</small></span></div>`:''}<div class="activity">✎ <span><strong>Atividade</strong><small>${esc(l.activity)}</small></span>${role==='aluno'?'<button onclick="essayModal()">Entregar</button>':''}</div>${role==='gestor'?`<button class="link" onclick="materialModal(${l.id})">＋ Adicionar material</button>`:''}</div></article>`).join('')}</section>`)}
function essays(){return shell(`<div class="heading"><h1>${role==='gestor'?'Redações da turma':'Minhas redações'}</h1><p>${role==='gestor'?'Abra um texto para corrigir.':'Seus textos e devolutivas.'}</p><button onclick="${role==='gestor'?'alert(\'Critérios salvos\')':'essayModal()'}">${role==='gestor'?'⚙ Critérios':'＋ Nova redação'}</button></div><section class="card list">${data.essays.map(e=>`<article><span class="file">▤</span><div><h3>${esc(e.title)}</h3><span class="status ${e.status==='Corrigida'?'ok':'wait'}">${esc(e.status)}</span></div>${e.grade?`<strong>${e.grade}<small>/1000</small></strong>`:''}</article>`).join('')}</section>`)}
function support(){return shell(`<div class="heading"><h1>Suporte</h1><p>Converse com ${role==='gestor'?'seus alunos':'o Léo'} por mensagem.</p></div><section class="card chat"><header><span class="avatar">${role==='gestor'?'AC':'<img src="leonardo-avatar.png" alt="Professor Léo">'}</span><div><h3>${role==='gestor'?'Ana Clara':'Professor Léo'}</h3><small>${esc(selectedClass)}</small></div><button onclick="cameraModal()">📹 Videochamada</button></header><div class="messages">${data.messages.map(m=>`<div class="bubble ${m.from===role?'mine':''}"><p>${esc(m.text)}</p><small>${esc(m.time)}</small></div>`).join('')}</div><form onsubmit="sendMessage(event)"><input id="msg" required placeholder="Escreva sua mensagem…"><button>➤</button></form></section>`)}
function sendMessage(e){e.preventDefault();const input=$('#msg');data.messages.push({id:Date.now(),from:role,text:input.value,time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})});save();render()}
function finance(){const students=data.students[selectedClass],received=students.reduce((s,a)=>s+a.paid,0),pending=students.reduce((s,a)=>s+a.pending,0);return shell(`<div class="heading"><small>GESTÃO FINANCEIRA</small><h1>Financeiro</h1><p>Acompanhe a situação de cada aluno.</p></div>${classPicker()}<div class="finance-summary"><section><small>Recebido</small><strong>${money(received)}</strong><span>${students.filter(s=>s.status==='Em dia').length} alunos em dia</span></section><section><small>Em aberto</small><strong>${money(pending)}</strong><span>${students.filter(s=>s.status!=='Em dia').length} pendências</span></section></div><section class="card finance-list"><div class="section-title"><h2>Alunos · ${esc(selectedClass)}</h2><span>${students.length} matriculados</span></div>${students.map(s=>`<article><span class="avatar">${s.initials}</span><div><h3>${esc(s.name)}</h3><small>Pago: ${money(s.paid)}</small></div><div class="student-money"><span class="status ${s.status==='Em dia'?'ok':s.status==='Atrasado'?'late':'wait'}">${esc(s.status)}</span><strong>${s.pending?money(s.pending):'Sem pendências'}</strong></div></article>`).join('')}</section>`)}
function profile(){return shell(`<div class="heading"><h1>Meu perfil</h1></div><div class="profile"><section class="card"><span class="avatar big">${role==='gestor'?'<img src="leonardo-avatar.png" alt="Leonardo Costa">':'AC'}</span><h2>${role==='gestor'?'Professor Léo':'Ana Clara'}</h2><p>${role==='gestor'?'Gestor do curso':'Turma ENEM 2026'}</p>${role==='gestor'?classPicker():''}<button class="outline" onclick="logout()">Sair</button></section><section class="profile-links">${role==='gestor'?'<button onclick="go(\'financeiro\')">💳 <span><strong>Financeiro</strong><small>Turmas, alunos e pendências</small></span>›</button>':''}<button onclick="go('trilhas')">📚 <span><strong>Minhas trilhas</strong><small>Conteúdos e atividades</small></span>›</button><button onclick="go('suporte')">💬 <span><strong>Suporte</strong><small>Mensagens e atendimento</small></span>›</button></section></div>`)}
function modal(title,body){const m=$('#modal');m.hidden=false;m.innerHTML=`<div class="backdrop" onclick="if(event.target===this)closeModal()"><section class="dialog"><button class="close" onclick="closeModal()">×</button><h2>${title}</h2>${body}</section></div>`} function closeModal(){const m=$('#modal');m.hidden=true;m.innerHTML=''}
function noticeModal(){modal('Publicar aviso',`<form onsubmit="addNotice(event)">${classPicker().replace('onchange="selectedClass=this.value;localStorage.setItem(\'leo-class\',selectedClass);render()"','id="notice-class"')}<label>Título<input id="notice-title" required></label><label>Aviso<textarea id="notice-text" required rows="4"></textarea></label><button>Publicar aviso</button></form>`)}
function addNotice(e){e.preventDefault();data.notices.unshift({id:Date.now(),schoolClass:$('#notice-class').value,title:$('#notice-title').value,text:$('#notice-text').value});save();closeModal();render()}
function materialModal(id){modal('Publicar material',`<form onsubmit="addMaterial(event)"><label>Aula<select id="mat-lesson">${data.lessons.map(l=>`<option value="${l.id}" ${l.id===id?'selected':''}>${esc(l.title)}</option>`).join('')}</select></label><label>Momento<select id="mat-phase"><option>Antes da aula</option><option>Durante a aula</option><option>Depois da aula</option></select></label><label>Título<input id="mat-title" required></label><button>Publicar material</button></form>`)}
function addMaterial(e){e.preventDefault();const l=data.lessons.find(x=>x.id===$('#mat-lesson').value*1);l.material=$('#mat-title').value;l.phase=$('#mat-phase').value;save();closeModal();render()}
function lessonModal(){modal('Incluir aula na trilha',`<form onsubmit="addLesson(event)"><label>Título<input id="lesson-title" required></label><label>Data e horário<input id="lesson-date" type="datetime-local" required></label><label>Conteúdo<textarea id="lesson-content" required rows="3"></textarea></label><label>Atividade<textarea id="lesson-activity" required rows="3"></textarea></label><button>Incluir na trilha</button></form>`)}
function addLesson(e){e.preventDefault();data.lessons.push({id:Date.now(),title:$('#lesson-title').value,date:new Date($('#lesson-date').value).toISOString(),content:$('#lesson-content').value,activity:$('#lesson-activity').value});save();closeModal();render()}
function essayModal(){modal('Nova redação',`<form onsubmit="addEssay(event)"><label>Tema<input id="essay-title" required></label><label>Texto<textarea id="essay-text" required rows="8"></textarea></label><button>Enviar redação</button></form>`)}
function addEssay(e){e.preventDefault();data.essays.unshift({id:Date.now(),title:$('#essay-title').value,status:'Em correção'});save();closeModal();render()}
async function cameraModal(){modal('Atendimento por vídeo',`<video id="preview" autoplay muted playsinline></video><p class="camera-note">A câmera está disponível para o atendimento quando a sala online estiver conectada.</p><button onclick="closeCamera()">Encerrar</button>`);try{window.localStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});$('#preview').srcObject=window.localStream}catch{$('.camera-note').textContent='Permita o acesso à câmera e ao microfone para iniciar.'}}
function closeCamera(){window.localStream?.getTracks().forEach(t=>t.stop());closeModal()}
function render(){if(!role){$('#app').innerHTML=welcome();return}const pages={inicio:home,trilhas:trails,redacoes:essays,suporte:support,perfil:profile,financeiro:finance};$('#app').innerHTML=(pages[view]||home)()}
window.addEventListener('hashchange',()=>{view=location.hash.slice(1)||'inicio';render()});render();
